-- DEPRECATED: this migration is intentionally empty.
-- The corrected schema is now fully contained in sql/schema.sql.
-- Run sql/schema.sql only. Do NOT run the old migration that replaced
-- zoma_get_login_email or changed show_whatsapp_2 defaults.
